// =================================================
// =                                               =
// = Sound.Autogenerated.cs                        =
// =                                               =
// = AUTO-GENERATED FILE - Do not edit!            =
// =                                               =
// =================================================

using System.Collections.Generic;

namespace Tobo.Audio
{
    public partial class Sound
    {
        public enum ID
        {
            None = 0,
            Move = 23645320,
            PhotoDrag = 930660399,
            PhotoDrop = 930660842,
            Select = 1410561011,
            SlotHover = -1850161273,
            Suspense_1_Loop = 1777985376,
            UIClick = 1713459037,
        }

        public static Sound Move => Get(ID.Move);
        public static Sound PhotoDrag => Get(ID.PhotoDrag);
        public static Sound PhotoDrop => Get(ID.PhotoDrop);
        public static Sound Select => Get(ID.Select);
        public static Sound SlotHover => Get(ID.SlotHover);
        public static Sound Suspense_1_Loop => Get(ID.Suspense_1_Loop);
        public static Sound UIClick => Get(ID.UIClick);

        internal static Dictionary<string, string> FilenameToSoundIDName { get; private set; } = new Dictionary<string, string>()
        {
        };

        internal static Dictionary<string, Sound.ID> SoundIDNameToSoundID { get; private set; } = new Dictionary<string, Sound.ID>()
        {
            { "None", Sound.ID.None },
            { "Move", Sound.ID.Move },
            { "PhotoDrag", Sound.ID.PhotoDrag },
            { "PhotoDrop", Sound.ID.PhotoDrop },
            { "Select", Sound.ID.Select },
            { "SlotHover", Sound.ID.SlotHover },
            { "Suspense_1_Loop", Sound.ID.Suspense_1_Loop },
            { "UIClick", Sound.ID.UIClick },
        };
    }
}

